import {
  Hospital,
  CalendarClock,
  ClipboardList,
  ScanLine,
  Stethoscope,
  Calculator,
  PenLine,
  Stamp,
  FileLock2,
  Receipt,
  Database,
  type LucideIcon,
} from "lucide-react";

export type PipelineKind = "source" | "step" | "gate" | "sink";
export type PipelineLane = "source" | "clinical" | "storage";

export type PipelineNode = {
  id: string;
  code: string;
  title: string;
  kind: PipelineKind;
  lane: PipelineLane;
  icon: LucideIcon;
  blurb: string;
  who: string;
  system: string;
  artifact: string;
  note: string;
  chips: string[];
};

export const pipelineNodes: PipelineNode[] = [
  {
    id: "epic",
    code: "00",
    title: "Epic EHR",
    kind: "source",
    lane: "source",
    icon: Hospital,
    blurb: "Physician places the imaging order in the chart",
    who: "Ordering clinician",
    system: "Epic",
    artifact: "ServiceRequest / ORM",
    note: "The exam does not start in Lumen. It starts as an order in Epic — accession, patient, modality, laterality, reason for exam. Lumen only accepts that packet. It never invents one.",
    chips: ["FHIR ServiceRequest", "accession", "MRN"],
  },
  {
    id: "order",
    code: "01",
    title: "Order",
    kind: "step",
    lane: "clinical",
    icon: CalendarClock,
    blurb: "Exam ordered and scheduled",
    who: "Front desk / scheduling",
    system: "Epic → Lumen",
    artifact: "Scheduled order",
    note: "The order lands, gets a slot, and becomes the only key the rest of the line will ever use. If scheduling fails, nothing downstream exists.",
    chips: ["order_id", "slot", "scheduled"],
  },
  {
    id: "exam",
    code: "02",
    title: "Exam",
    kind: "step",
    lane: "clinical",
    icon: ClipboardList,
    blurb: "Technologist opens the structured worksheet",
    who: "Sonographer / tech",
    system: "Lumen",
    artifact: "Structured worksheet",
    note: "The worksheet is bound to the Epic order. No free-floating notes, no second patient context. The tech works inside the packet.",
    chips: ["worksheet", "operator"],
  },
  {
    id: "imaging",
    code: "03",
    title: "Imaging",
    kind: "step",
    lane: "clinical",
    icon: ScanLine,
    blurb: "Stills, cine, and DICOM captured",
    who: "Modality",
    system: "Ultrasound / PACS ingest",
    artifact: "Image series",
    note: "Files attach to the same order. Nothing is named by hand. DICOM tags must match the accession that Epic issued.",
    chips: ["DICOM", "cine", "accession match"],
  },
  {
    id: "measurements",
    code: "04",
    title: "Measurements",
    kind: "step",
    lane: "clinical",
    icon: Stethoscope,
    blurb: "Segment-level values recorded",
    who: "Technologist + assist",
    system: "Lumen",
    artifact: "Measurement set",
    note: "Values write into the worksheet, not a side spreadsheet. Every number keeps a pointer to the frame it came from.",
    chips: ["segments", "traceable"],
  },
  {
    id: "calculations",
    code: "05",
    title: "Calculations",
    kind: "gate",
    lane: "clinical",
    icon: Calculator,
    blurb: "Ratios and derived values computed",
    who: "Pipeline (gated)",
    system: "Lumen",
    artifact: "Derived values",
    note: "Derived only from recorded measurements. No silent edits. This is the first hard gate: if the inputs are incomplete, calculation refuses.",
    chips: ["derived", "immutable"],
  },
  {
    id: "interpretation",
    code: "06",
    title: "Interpretation",
    kind: "step",
    lane: "clinical",
    icon: PenLine,
    blurb: "Clinical criteria applied to findings",
    who: "Physician workspace",
    system: "Lumen",
    artifact: "Draft findings",
    note: "Criteria run against the packet. Findings stay attached to the measurements they came from — not a separate narrative.",
    chips: ["criteria", "findings"],
  },
  {
    id: "review",
    code: "07",
    title: "Physician Review",
    kind: "gate",
    lane: "clinical",
    icon: Stamp,
    blurb: "Sign-off against facility protocol",
    who: "Attending",
    system: "Lumen",
    artifact: "Signed interpretation",
    note: "The human gate. Nothing downstream — billing, EMR, PACS finalize — moves without this seal.",
    chips: ["sign-off", "protocol"],
  },
  {
    id: "report",
    code: "08",
    title: "Final Report",
    kind: "step",
    lane: "clinical",
    icon: FileLock2,
    blurb: "Locked, addendable clinical record",
    who: "Health record",
    system: "Lumen",
    artifact: "Final report",
    note: "Locked body, addenda only. The packet is now a record. Storage is allowed.",
    chips: ["locked", "addendum-only"],
  },
  {
    id: "billing",
    code: "09",
    title: "Billing Prep",
    kind: "sink",
    lane: "storage",
    icon: Receipt,
    blurb: "Structured handoff to revenue cycle",
    who: "Revenue cycle",
    system: "RevCycle",
    artifact: "Charge ticket",
    note: "Codes come from the signed packet. No re-keying from a Word doc. The charge follows the report, not the other way around.",
    chips: ["CPT", "handoff"],
  },
  {
    id: "storage",
    code: "10",
    title: "EMR / PACS",
    kind: "sink",
    lane: "storage",
    icon: Database,
    blurb: "Delivered to downstream systems",
    who: "Integrations",
    system: "Epic + PACS",
    artifact: "Stored study + report",
    note: "Same packet, two doors. The signed report returns to Epic. The images land in PACS under the original accession. Reporting and imaging stay twins.",
    chips: ["ORU / FHIR", "C-STORE", "Epic", "PACS"],
  },
];
